Repository D5ng/team-mogazoa-sprint, pull requests merged in 2024-09, with the labels that each got.

#3 Docs: PR Template 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📝 Documentation

#7 [#2]✨ feat: FSD구조 적용
  pages/api/hello.ts
  pages/index.tsx
  public/favicon.ico
  public/next.svg
  public/vercel.svg
  src/app/provider/.gitkeep
  src/app/styles/globals.css
  src/entities/.gitkeep
  src/features/.gitkeep
  src/pages/.gitkeep
  src/shared/.gitkeep
  src/widgets/.gitkeep
  tailwind.config.ts
  tsconfig.json
Labels: ✨ Feature

#9 🔧 Config: 타입 관련 lint 추가 적용
  .eslintrc.json
  package.json
  yarn.lock
Labels: 📝 Documentation

#12 ✨ Feat: Button 컴포넌트
  .eslintrc.json
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  .yarn/releases/yarn-4.4.1.cjs
  .yarnrc.yml
  package.json
  pages/_app.tsx
  src/app/styles/globals.css
  src/app/styles/reset.css
  src/shared/ui/button/Button.constants.ts
  src/shared/ui/button/Button.stories.tsx
  src/shared/ui/button/Button.tsx
  src/shared/ui/button/Button.type.ts
  tailwind.config.ts
  tsconfig.json
  yarn.lock
Labels: ✨ Feature, 💄 UI

#18 ✨ Feat: FormField 컴포넌트 제작
  package.json
  pages/_app.tsx
  pages/sign-up/index.tsx
  src/app/styles/globals.css
  src/app/styles/reset.css
  src/shared/lib/form-validation.ts
  src/shared/ui/form-field/FormField.tsx
  src/shared/ui/form-field/FormField.type.ts
  src/shared/ui/form/Form.tsx
  src/widgets/.gitkeep
  yarn.lock
Labels: ✨ Feature, 💄 UI

#16 ✨ Feat: Dropdown 컴포넌트
  src/app/images/icons/dropdown-arrow.svg
  src/shared/hooks/index.ts
  src/shared/hooks/useOutsideClick.ts
  src/shared/hooks/useSelect.ts
  src/shared/hooks/useToggle.ts
  src/shared/ui/dropdown/Dropdown.stories.tsx
  src/shared/ui/dropdown/Dropdown.tsx
  src/shared/ui/dropdown/Dropdown.type.ts
Labels: ✨ Feature, 💄 UI

#20 ✨ Feat: Loading 컴포넌트 추가
  src/app/styles/globals.css
  src/shared/ui/button/Button.stories.tsx
  src/shared/ui/button/Button.tsx
  src/shared/ui/loading/Loading.tsx
Labels: 💄 UI

#22 📦 Chore: TanstackQuery, Axios 패키지 추가
  package.json
  yarn.lock
Labels: 📝 Documentation

#27 ✨ feat: ranking 컴포넌트 제작
  next.config.mjs
  pages/test.tsx
  src/shared/hooks/useChipVariant.ts
  src/shared/ui/profileImage/ProfileImage.tsx
  src/shared/ui/profileImage/ProfileImage.type.ts
  src/widgets/ranking/Ranking.tsx
  src/widgets/ranking/Ranking.types.ts
  src/widgets/ranking/RankingChip.constant.ts
  src/widgets/ranking/RankingChip.tsx
  src/widgets/ranking/RankingUi.tsx
  tailwind.config.ts
  yarn.lock
Labels: ✨ Feature

#24 ✨ Feat: Dropdown 최신순
  pages/dong/index.tsx
  src/shared/ui/dropdown/Dropdown.constants.ts
  src/shared/ui/dropdown/Dropdown.stories.tsx
  src/shared/ui/dropdown/Dropdown.tsx
  src/shared/ui/dropdown/Dropdown.type.ts
  yarn.lock
Labels: 💄 UI

#26 ✨ Feat: Category Chip 컴포넌트 구현
  src/app/images/icons/heart-icon.svg
  src/app/images/icons/review-icon.svg
  src/app/images/icons/star-rating-icon.svg
  src/features/product-detail/components/index.ts
  src/features/product-detail/components/statistics/calculate/ProductComparisonMessage.tsx
  src/features/product-detail/components/statistics/calculate/ProductComparisonMessage.type.ts
  src/features/product-detail/components/statistics/calculate/helper/CountMessage.tsx
  src/features/product-detail/components/statistics/calculate/helper/StarRatingMessage.tsx
  src/features/product-detail/components/statistics/calculate/helper/index.ts
  src/features/product-detail/components/statistics/index.ts
  src/features/product-detail/components/statistics/item/StatisticsListItem.tsx
  src/features/product-detail/components/statistics/list/StatisticsList.tsx
  src/features/product-detail/components/statistics/wrapper/StatisticsWrapper.tsx
  src/features/product-detail/constants/Statistics.constants.ts
  src/features/product-detail/constants/index.ts
  src/features/product-detail/layout/ProductDetailLayout.tsx
  src/features/product-detail/layout/index.ts
  src/features/product-detail/storybook/Statistics.stories.tsx
  src/features/product-detail/types/index.ts
  src/shared/ui/dropdown/Dropdown.constants.ts
  src/shared/ui/dropdown/Dropdown.stories.tsx
  src/shared/ui/dropdown/Dropdown.tsx
  src/widgets/category-chip/CategoryChip.constants.ts
  src/widgets/category-chip/CategoryChip.stories.tsx
  src/widgets/category-chip/CategoryChip.tsx
  src/widgets/category-chip/CategoryChip.type.ts
  yarn.lock
Labels: 💄 UI

#31 ✨ Feat: Product-detail 통계 컴포넌트
  src/app/images/icons/heart-icon.svg
  src/app/images/icons/review-icon.svg
  src/app/images/icons/star-rating-icon.svg
  src/features/product-detail/components/index.ts
  src/features/product-detail/components/statistics/calculate/ProductComparisonMessage.tsx
  src/features/product-detail/components/statistics/calculate/ProductComparisonMessage.type.ts
  src/features/product-detail/components/statistics/calculate/helper/CountMessage.tsx
  src/features/product-detail/components/statistics/calculate/helper/StarRatingMessage.tsx
  src/features/product-detail/components/statistics/calculate/helper/index.ts
  src/features/product-detail/components/statistics/index.ts
  src/features/product-detail/components/statistics/item/StatisticsListItem.tsx
  src/features/product-detail/components/statistics/list/StatisticsList.tsx
  src/features/product-detail/components/statistics/wrapper/StatisticsWrapper.tsx
  src/features/product-detail/constants/Statistics.constants.ts
  src/features/product-detail/constants/index.ts
  src/features/product-detail/layout/ProductDetailLayout.tsx
  src/features/product-detail/layout/index.ts
  src/features/product-detail/storybook/Statistics.stories.tsx
  src/features/product-detail/types/index.ts
Labels: ✨ Feature, 💄 UI

#39 🐛 Fix: Dropdown 버그
  src/shared/ui/dropdown/Dropdown.constants.ts
  src/shared/ui/dropdown/Dropdown.stories.tsx
  src/shared/ui/dropdown/Dropdown.tsx
  yarn.lock
Labels: 🐛 Bug

#29 ✨ Feat: TextFiledInput 컴포넌트 및 자동완성 기능
  pages/sign-up/index.tsx
  pages/wow/index.tsx
  src/app/styles/globals.css
  src/shared/hooks/index.ts
  src/shared/hooks/useAutoComplete.ts
  src/shared/ui/autocompleteSuggestions/AutocompleteSuggestions.tsx
  src/shared/ui/autocompleteSuggestions/AutocompleteSuggestions.type.ts
  src/shared/ui/form-field/FormField.tsx
  src/shared/ui/text-field-input/TextFieldInput.tsx
  src/shared/ui/text-field-input/TextFieldInput.type.ts
  yarn.lock
Labels: ✨ Feature, 💄 UI

#52 🐛 Fix: Dropdown 버그
  src/shared/ui/dropdown/Dropdown.constants.ts
  src/shared/ui/dropdown/Dropdown.tsx
  src/shared/ui/dropdown/Dropdown.type.ts
Labels: 🐛 Bug

#54 ♻️ [#25] Refactor: 카테고리 수정
  pages/dong/index.tsx
  src/widgets/category-chip/CategoryChip.constants.ts
Labels: ♻️ Refactor

#41 ✨ Feat: Product-detail-review 컴포넌트
  package.json
  pages/_app.tsx
  pages/dong/index.tsx
  pages/test.tsx
  public/images/add.svg
  public/images/addImage.svg
  public/images/category.svg
  public/images/close.svg
  public/images/dropDown.svg
  public/images/dropUp.svg
  public/images/empty-review.svg
  public/images/emptyHeart.svg
  public/images/emptyThumb.svg
  public/images/eyeOff.svg
  public/images/eyeOn.svg
  public/images/google.svg
  public/images/hamburger.svg
  public/images/heart.svg
  public/images/kakao.svg
  public/images/profile.svg
  public/images/review.svg
  public/images/search.svg
  public/images/share.svg
  public/images/star.svg
  public/images/thumb.svg
  public/test/review-profile.jpg
  src/app/icons/index.ts
  src/app/styles/globals.css
  src/app/types/index.ts
  src/app/types/review.type.ts
  src/features/product-detail/components/index.ts
  src/features/product-detail/components/review/contents/ReviewContents.tsx
  src/features/product-detail/components/review/contents/review-images/ReviewImages.tsx
  src/features/product-detail/components/review/contents/thumbs-button/ThumbsButton.tsx
  src/features/product-detail/components/review/index.ts
  src/features/product-detail/components/review/item/ReviewListItem.tsx
  src/features/product-detail/components/review/latest-dropdown/LatestDropdown.tsx
  src/features/product-detail/components/review/list/ReviewEmptyList.tsx
  src/features/product-detail/components/review/list/ReviewList.tsx
  src/features/product-detail/components/review/profile/ReviewProfile.tsx
  src/features/product-detail/components/review/profile/rating/ReviewRating.tsx
  src/features/product-detail/components/review/wrapper/ReviewWrapper.tsx
  src/features/product-detail/constants/Review.constants.ts
  src/features/product-detail/constants/Statistics.constants.ts
  src/features/product-detail/constants/index.ts
  src/features/product-detail/layout/ProductDetailLayout.tsx
  src/features/product-detail/storybook/Review.stories.tsx
  src/features/product-detail/storybook/Statistics.stories.tsx
  src/shared/ui/dropdown/Dropdown.tsx
  src/shared/ui/dropdown/Dropdown.type.ts
  src/widgets/Gnb/Gnb-Input.tsx
  src/widgets/side-menu/MenuTaps.tsx
  src/widgets/side-menu/SideMenu.tsx
  yarn.lock
Labels: ✨ Feature, 💄 UI

#45 ✨ Feat : sideMenu 컴포넌트 제작 (브랜치 리네임)
  src/app/styles/globals.css
  src/widgets/Gnb/Gnb-ui-Mobile.tsx
  src/widgets/Gnb/Gnb.stories.ts
  src/widgets/side-menu/SideMenu.stories.ts
  src/widgets/side-menu/SideMenu.tsx
Labels: ✨ Feature

#48 ✨Feat : product-cards 컴포넌트 제작 및 반응형 작업
  pages/_app.tsx
  pages/test.tsx
  public/images/apple_watch.svg
  public/images/camera.svg
  public/images/dison.svg
  public/images/settop_box.svg
  public/images/sony.svg
  public/images/speaker.svg
  src/app/icons/index.ts
  src/app/styles/globals.css
  src/features/product-detail/components/index.ts
  src/features/product-detail/components/review/contents/ReviewContents.tsx
  src/features/product-detail/components/review/index.ts
  src/features/product-detail/components/review/item/ReviewListItem.tsx
  src/features/product-detail/constants/Review.constants.ts
  src/widgets/Gnb/Gnb.tsx
  src/widgets/products-card/ProductCard.mock.ts
  src/widgets/products-card/ProductCard.tsx
  src/widgets/products-card/ProductCard.types.ts
  src/widgets/products-card/ProductCardItem.tsx
Labels: ✨ Feature

#56 ✨ Feat: Product-detail-info 컴포넌트
  pages/dong/index.tsx
  public/test/product_image.png
  src/features/product-detail/components/index.ts
  src/features/product-detail/components/product-info/clip-board-button/ClipBoardButton.tsx
  src/features/product-detail/components/product-info/index.ts
  src/features/product-detail/components/product-info/kakao-share-button/KaKaoShareButton.tsx
  src/features/product-detail/components/product-info/like-button/LikeButton.tsx
  src/features/product-detail/components/product-info/product-contents/ProductContents.tsx
  src/features/product-detail/components/product-info/product-image/ProductImage.tsx
  src/features/product-detail/components/product-info/wrapper/ProductInfoWrapper.tsx
  src/features/product-detail/storybook/ProductInfo.stories.tsx
  src/shared/ui/button/Button.constants.ts
  tailwind.config.ts
Labels: 💄 UI

#51 ✨ Feat: TextBoxInput, ImageInput 제작 및 이전 코드 리팩토링
  pages/sign-up/index.tsx
  pages/wow/index.tsx
  public/images/addImage.svg
  public/images/close.svg
  src/app/styles/globals.css
  src/features/auth/components/form-field/FormField.tsx
  src/features/auth/components/form-field/FormField.type.ts
  src/features/auth/lib/form-validation.ts
  src/shared/hooks/index.ts
  src/shared/hooks/useAutoComplete.ts
  src/shared/hooks/useKeyboardSelect.ts
  src/shared/ui/autocomplete-field/AutocompleteField.tsx
  src/shared/ui/autocomplete-field/AutocompleteField.type.ts
  src/shared/ui/autocompleteSuggestions/AutocompleteSuggestions.tsx
  src/shared/ui/autocompleteSuggestions/AutocompleteSuggestions.type.ts
  src/shared/ui/form/Form.tsx
  src/shared/ui/index.ts
  src/shared/ui/input/image-input/ImageInput.tsx
  src/shared/ui/input/image-input/ImageInput.type.ts
  src/shared/ui/input/index.ts
  src/shared/ui/input/text-box-input/TextBoxInput.tsx
  src/shared/ui/input/text-box-input/TextBoxInput.type.ts
  src/shared/ui/input/text-field-input/TextFieldInput.tsx
  src/shared/ui/input/text-field-input/TextFieldInput.type.ts
  src/shared/ui/text-field-input/TextFieldInput.tsx
Labels: ✨ Feature, ♻️ Refactor

#60 🐛 Fix: 전반적인 input 에러 수정
  pages/jb/index.tsx
  pages/sign-up/index.tsx
  public/images/addImage.svg
  public/images/close.svg
  src/app/styles/globals.css
  src/shared/ui/form/Form.tsx
  src/shared/ui/input/image-input/ImageInput.tsx
  src/shared/ui/input/image-input/ImageInput.type.ts
  src/shared/ui/input/index.ts
  src/shared/ui/input/text-box-input/TextBoxInput.tsx
  src/shared/ui/input/text-box-input/TextBoxInput.type.ts
  src/shared/ui/input/text-field-input/TextFieldInput.tsx
  src/shared/ui/input/text-field-input/TextFieldInput.type.ts
  src/shared/ui/input/textarea-input/TextareaInput.tsx
  src/shared/ui/input/textarea-input/TextareaInput.type.ts
Labels: 🐛 Bug

#58 ✨ Feat: 공통 Modal Component 만들기
  src/shared/ui/modal/Modal.tsx
  src/shared/ui/modal/Modal.type.ts
Labels: 💄 UI

#63 ✨ Feat: 상품 추가하기 모달
  package.json
  pages/_document.tsx
  pages/dong/index.tsx
  pages/jb/index.tsx
  public/images/addImage.svg
  src/app/types/index.ts
  src/app/types/product.type.ts
  src/features/product-add-modal/components/category-dropdown/CategoryDropdown.tsx
  src/features/product-add-modal/components/index.ts
  src/features/product-add-modal/components/modal/ProductAddModal.tsx
  src/shared/ui/button/Button.tsx
  src/shared/ui/dropdown/Dropdown.tsx
  src/shared/ui/dropdown/Dropdown.type.ts
  src/shared/ui/index.ts
  src/shared/ui/input/image-input/ImageInput.tsx
  src/shared/ui/input/image-input/ImageInput.type.ts
  src/shared/ui/input/text-field-input/TextFieldInput.type.ts
  src/shared/ui/modal/Modal.tsx
  src/widgets/category-chip/CategoryChip.constants.ts
  src/widgets/category-chip/CategoryChip.stories.tsx
  src/widgets/category-chip/CategoryChip.tsx
  tailwind.config.ts
  yarn.lock
Labels: 💄 UI

#67 ✨ Feat: Button 반응형 추가
  src/shared/ui/button/Button.tsx
Labels: 💄 UI

#69 ✨ Feat: Dropdown 반응형 추가
  src/shared/ui/dropdown/Dropdown.constants.ts
Labels: 💄 UI

#70 ✨ Feat: 회원가입, 로그인 페이지 생성 및 기능 구현
  pages/sign-in/index.tsx
  pages/sign-up/index.tsx
  src/pages/.gitkeep
  src/pages/auth/sign-in/SignInPage.tsx
  src/pages/auth/sign-up/SignUpPage.tsx
  src/pages/index.ts
  src/shared/.gitkeep
  src/shared/config/axios-instance.ts
  src/shared/ui/form-field/FormField.tsx
  src/shared/ui/form-field/FormField.type.ts
  src/shared/ui/form/Form.tsx
  src/shared/ui/form/Form.type.ts
  src/widgets/auth/api/index.ts
  src/widgets/auth/api/postSignIn.ts
  src/widgets/auth/api/postSignUp.ts
  src/widgets/auth/components/index.ts
  src/widgets/auth/components/sign-in-field/SignInField.tsx
  src/widgets/auth/components/sign-up-field/SignUpField.tsx
  src/widgets/auth/hooks/index.ts
  src/widgets/auth/hooks/useAuth.ts
  src/widgets/auth/lib/form-validation.ts
  src/widgets/auth/lib/getCookies.ts
  src/widgets/auth/types/auth.type.ts
Labels: ✨ Feature

#73 ♻️ Refactor: Product-detail-page 리팩토링
  src/features/product-detail/components/product-info/product-contents/ProductContents.tsx
  src/features/product-detail/components/product-info/wrapper/ProductInfoWrapper.tsx
  src/features/product-detail/components/statistics/list/StatisticsList.tsx
  src/features/product-detail/components/statistics/wrapper/StatisticsWrapper.tsx
  src/features/product-detail/types/index.ts
Labels: ♻️ Refactor

#76 ✨ Feat: Product-add-button 컴포넌트 추가
  pages/dong/index.tsx
  src/widgets/product-add-button/ProductAddButton.tsx
Labels: 💄 UI

#79 ✨ Feat: API, Types 폴더 구조 변경
  src/shared/api/auth.api.ts
  src/shared/api/category.api.ts
  src/shared/api/follow.api.ts
  src/shared/api/index.ts
  src/shared/api/product.api.ts
  src/shared/api/review.api.ts
  src/shared/api/upload.api.ts
  src/shared/api/user.api.ts
  src/shared/types/auth/index.ts
  src/shared/types/category/index.ts
  src/shared/types/follow/index.ts
  src/shared/types/index.ts
  src/shared/types/product/index.ts
  src/shared/types/product/product-detail.type.ts
  src/shared/types/product/product-favorite.type.ts
  src/shared/types/product/product-review.type.ts
  src/shared/types/product/product.type.ts
  src/shared/types/review/index.ts
  src/shared/types/upload/index.ts
  src/shared/types/user/index.ts
  src/shared/types/user/user.type.ts
Labels: ✨ Feature

#92 ✨ Feat: 구글 로그인 및 토큰 axiosInstance 헤더에 추가
  package.json
  pages/_app.tsx
  pages/auth/google/callback.tsx
  pages/auth/kakao/callback.tsx
  pages/jb/index.tsx
  pages/oauth/google/index.tsx
  pages/oauth/kakao/index.tsx
  src/app/provider/.gitkeep
  src/app/provider/KakaoScript.tsx
  src/pages/auth/sign-in/SignInPage.tsx
  src/pages/auth/sign-up/SignUpPage.tsx
  src/pages/auth/social-sign-up/SocialSignUpPage.tsx
  src/shared/api/auth.api.ts
  src/shared/config/axios-instance.ts
  src/shared/hooks/useProduct.ts
  src/shared/store/authStore.ts
  src/shared/types/auth/auth.type.ts
  src/shared/types/auth/index.ts
  src/shared/types/auth/kakao.d.ts
  src/shared/ui/form-field/FormField.tsx
  src/shared/ui/form-field/FormField.type.ts
  src/widgets/auth/api/auth.api.ts
  src/widgets/auth/api/index.ts
  src/widgets/auth/api/postSignIn.ts
  src/widgets/auth/api/postSignUp.ts
  src/widgets/auth/components/index.ts
  src/widgets/auth/components/nickname-field/NicknameField.tsx
  src/widgets/auth/components/nickname-field/NicknameField.type.ts
  src/widgets/auth/components/sign-in-field/SignInField.tsx
  src/widgets/auth/components/sign-up-field/SignUpField.tsx
  src/widgets/auth/components/sns-field/SnsField.tsx
  src/widgets/auth/hooks/index.ts
  src/widgets/auth/hooks/useAuth.ts
  src/widgets/auth/hooks/useOAuth.ts
  src/widgets/auth/lib/form-validation.ts
  src/widgets/auth/lib/getCookies.ts
  src/widgets/auth/types/auth.type.ts
  src/widgets/product/Gnb/Gnb-Input.tsx
  yarn.lock
Labels: ✨ Feature

#95 ✨ Feat: input 에러메시지 작업
  src/shared/lib/input-validation.ts
  src/shared/ui/error-message/ErrorMessage.tsx
  src/shared/ui/error-message/ErrorMessage.type.ts
  src/shared/ui/form-field/FormField.tsx
  src/shared/ui/input/text-field-input/TextFieldInput.tsx
  src/shared/ui/input/text-field-input/TextFieldInput.type.ts
  src/shared/ui/input/textarea-input/TextareaInput.tsx
  src/shared/ui/input/textarea-input/TextareaInput.type.ts
  src/widgets/auth/components/sign-in-field/SignInField.tsx
  src/widgets/auth/components/sign-up-field/SignUpField.tsx
  src/widgets/product-add-modal/components/modal/ProductAddModal.tsx
Labels: ✨ Feature

#99 🐛 Fix: 불필요한 파일 및 폴더 삭제.
  src/shared/store/authStore.ts
  src/widgets/product-review-modal/components/form/ProductReviewForm.tsx
  src/widgets/product-review-modal/components/form/ProductReviewImageUpload.tsx
  src/widgets/product-review-modal/components/form/defaultValues.ts
  src/widgets/product-review-modal/components/modal/ProductReviewModal.tsx
Labels: 🐛 Bug

#101 ✨ Feat: Auth (cookies-next 마이그레이션)
  package.json
  pages/product/[id]/index.tsx
  src/shared/config/axios-instance.ts
  src/shared/hooks/index.ts
  src/shared/hooks/useLogout.ts
  src/widgets/auth/api/auth.api.ts
  src/widgets/auth/components/sign-in-field/SignInField.tsx
  src/widgets/auth/components/sign-up-field/SignUpField.tsx
  src/widgets/auth/hooks/index.ts
  src/widgets/auth/hooks/useAuth.ts
  src/widgets/auth/hooks/useSignIn.ts
  src/widgets/auth/hooks/useSignUp.ts
  yarn.lock
Labels: ✨ Feature, ♻️ Refactor

#103 🐛 Fix: Product-review-modal 사용성 문제.
  src/widgets/product-review-modal/components/form/ReviewCreateForm.tsx
  src/widgets/product-review-modal/components/form/ReviewUpdateForm.tsx
Labels: 🐛 Bug

#108 ✨ Feat: 소셜 로그인
  pages/api/google/signIn.ts
  pages/api/google/signUp.ts
  pages/api/kakao/signIn.tsx
  pages/api/kakao/signup.tsx
  pages/auth/google/callback.tsx
  pages/auth/kakao/callback.tsx
  pages/auth/oauth-sign-up/google.tsx
  pages/auth/oauth-sign-up/kakao.tsx
  pages/oauth/google/index.tsx
  pages/oauth/kakao/index.tsx
  src/app/provider/Oauth.ts
  src/pages/auth/oauth-sign-up/SocialSignUpPage.tsx
  src/pages/auth/sign-in/SignInPage.tsx
  src/pages/auth/social-sign-up/SocialSignUpPage.tsx
  src/shared/constants/index.ts
  src/shared/constants/social.constants.ts
  src/shared/utils/index.ts
  src/shared/utils/token.utils.ts
  src/widgets/auth/components/index.ts
  src/widgets/auth/components/nickname-field/NicknameField.tsx
  src/widgets/auth/components/oauth-field/OauthField.tsx
  src/widgets/auth/hooks/index.ts
  src/widgets/auth/hooks/useOAuth.ts
Labels: ✨ Feature, ♻️ Refactor

#110 ✨Feat: 프로필 페이지 상품 섹션
  pages/my-profile/index.tsx
  src/app/styles/globals.css
  src/pages/profile/Profile.tsx
  src/shared/api/user.api.ts
  src/shared/hooks/query/user.query.ts
  src/shared/types/user/user.type.ts
  src/shared/ui/dropdown/Dropdown.tsx
  src/shared/ui/dropdown/Dropdown.type.ts
  src/widgets/product/gnb/GnbMenu.tsx
  src/widgets/profile-follow-modal/follow/Follow.tsx
  src/widgets/profile-follow-modal/followees-list/FolloweesList.tsx
  src/widgets/profile-follow-modal/follower-list/FollowerList.tsx
  src/widgets/profile-follow-modal/index.ts
  src/widgets/profile-follow-modal/modal/ProfileFolloweesModal.tsx
  src/widgets/profile-follow-modal/modal/ProfileFollowerModal.tsx
  src/widgets/profile/MockCardItem.tsx
  src/widgets/profile/components/button/FolloweesButton.tsx
  src/widgets/profile/components/button/FollowerButton.tsx
  src/widgets/profile/components/product-card-section/ProductCardSection.tsx
  src/widgets/profile/components/product-card-section/RegisteredProducts.tsx
  src/widgets/profile/components/product-card-section/ReviewedProducts.tsx
  src/widgets/profile/components/product-card-section/WishListedProducts.tsx
  src/widgets/profile/components/product-card-section/category/CategoryPc.tsx
  src/widgets/profile/components/product-card-section/category/CategoryTablet.tsx
  src/widgets/profile/components/product-card-section/index.ts
  src/widgets/profile/components/product-card-section/products/CreatedProducts/CreatedProducts.tsx
  src/widgets/profile/components/product-card-section/products/CreatedProducts/CreatedProductsList.tsx
  src/widgets/profile/components/product-card-section/products/FavoriteProducts/FavoriteProducts.tsx
  src/widgets/profile/components/product-card-section/products/FavoriteProducts/FavoriteProductsList.tsx
  src/widgets/profile/components/product-card-section/products/ReviewedProducts/ReviewedProducts.tsx
  src/widgets/profile/components/product-card-section/products/ReviewedProducts/ReviewedProductsList.tsx
  src/widgets/profile/components/profile-card/MyProfileCard.tsx
  src/widgets/profile/components/profile-card/UserProfileCard.tsx
  src/widgets/profile/components/profile-card/index.ts
  src/widgets/profile/types/Category.type.ts
Labels: ✨ Feature

#113 ✨ Feat: 페이지 접근 권한 보호
  middleware.ts
Labels: ✨ Feature

#115 ✨🐛 Feat/Fix : toast 전역 적용 & 프로필 분기를 위한 useUserStore 로직 변경
  middleware.ts
  package.json
  pages/_app.tsx
  pages/profile/my/index.tsx
  src/app/styles/globals.css
  src/app/styles/toastify-style.css
  src/pages/profile/Profile.tsx
  src/shared/hooks/query/user.query.ts
  src/shared/hooks/useLogout.ts
  src/shared/store/userStore.ts
  src/shared/ui/form-field/FormField.tsx
  src/shared/ui/gnb/GnbMenu.tsx
  src/shared/ui/gnb/GnbProductSearchInput.tsx
  src/shared/utils/index.ts
  src/shared/utils/toast-check-auth.utils.ts
  src/widgets/auth/components/sign-in-field/SignInField.tsx
  src/widgets/auth/components/sign-up-field/SignUpField.tsx
  src/widgets/auth/hooks/useSignIn.ts
  src/widgets/auth/hooks/useSignUp.ts
  src/widgets/product/product-detail/components/product-info/product-contents/ClipBoardButton.tsx
  src/widgets/product/product-detail/components/product-info/product-contents/ReviewButton.tsx
  src/widgets/product/product-detail/components/review/contents/thumbs-button/ThumbsButton.tsx
  src/widgets/product/product-detail/hooks/useCreateReviewForm.ts
  src/widgets/product/product-home/components/product-add-button/ProductAddButton.tsx
  src/widgets/product/product-home/hooks/useProductAddForm.ts
  src/widgets/profile/components/product-card-section/index.ts
  src/widgets/profile/components/product-card-section/products/CreatedProducts.tsx
  src/widgets/profile/components/product-card-section/products/CreatedProducts/CreatedProducts.tsx
  src/widgets/profile/components/product-card-section/products/FavoriteProducts.tsx
  src/widgets/profile/components/product-card-section/products/FavoriteProducts/FavoriteProducts.tsx
  src/widgets/profile/components/product-card-section/products/ProductsList.tsx
  src/widgets/profile/components/product-card-section/products/ReviewedProducts.tsx
  src/widgets/profile/components/product-card-section/products/ReviewedProducts/ReviewedProducts.tsx
  src/widgets/profile/components/product-card-section/products/created-products/CreatedProductsList.tsx
  src/widgets/profile/components/product-card-section/products/favorite-products/FavoriteProductsList.tsx
  src/widgets/profile/components/product-card-section/products/reviewed-products/ReviewedProductsList.tsx
  src/widgets/profile/components/profile-card/card-contents/UserProfileButton.tsx
  src/widgets/profile/components/profile-card/card/MyProfileCard.tsx
  src/widgets/profile/components/profile-card/card/UserProfileCard.tsx
  src/widgets/profile/components/profile-follow-modal/follower-list/FollowerList.tsx
  src/widgets/profile/components/profile-follow-modal/modal/ProfileFolloweesModal.tsx
  src/widgets/profile/components/profile-follow-modal/modal/ProfileFollowerModal.tsx
  src/widgets/profile/hooks/useProfileEditForm.ts
  yarn.lock
Labels: ✨ Feature, 🐛 Bug

#118 ✨ Feat: 상품 편집 모달 추가 [리뷰 반영]
  pages/product/[id]/index.tsx
  src/pages/product/detail/ProductDetail.tsx
  src/shared/hooks/mutate/product-detail.mutate.ts
  src/shared/ui/input/image-input/ImageInput.tsx
  src/widgets/product/product-detail/components/index.ts
  src/widgets/product/product-detail/components/product-info/info/ProductInfo.tsx
  src/widgets/product/product-detail/components/product-info/product-contents/ProductContents.tsx
  src/widgets/product/product-detail/components/product-info/product-contents/ProductUpdateButton.tsx
  src/widgets/product/product-detail/components/product-update-modal/category-dropdown/CategoryDropdown.tsx
  src/widgets/product/product-detail/components/product-update-modal/form/ProductImageUpload.tsx
  src/widgets/product/product-detail/components/product-update-modal/form/ProductUpdateForm.tsx
  src/widgets/product/product-detail/components/product-update-modal/form/defaultValues.ts
  src/widgets/product/product-detail/components/product-update-modal/image-upload/ProductImageUpload.tsx
  src/widgets/product/product-detail/components/product-update-modal/index.ts
  src/widgets/product/product-detail/components/product-update-modal/modal/ProductUpdateModal.tsx
  src/widgets/product/product-detail/hooks/index.ts
  src/widgets/product/product-detail/hooks/useUpdateProductForm.ts
Labels: ✨ Feature

#120 ✨ Feat: 상품 추가 모달 [뮤테이션 적용]
  src/shared/hooks/mutate/index.ts
  src/shared/hooks/mutate/product.mutate.ts
  src/widgets/product/product-home/components/product-add-modal/form/ProductAddForm.tsx
  src/widgets/product/product-home/hooks/useProductAddForm.ts
Labels: ✨ Feature

#131 ♻️ Refactor : productCard ui, mainpage ssr, category메뉴 및 gnb 수정
  pages/category/[id]/index.tsx
  pages/index.tsx
  src/pages/product/Product.tsx
  src/shared/hooks/useToggle.ts
  src/shared/ui/gnb/Gnb.tsx
  src/shared/ui/gnb/GnbHamburgerButton.tsx
  src/shared/ui/gnb/GnbItemMobile.tsx
  src/shared/ui/gnb/GnbItemPc.tsx
  src/shared/ui/gnb/GnbMenu.tsx
  src/shared/ui/gnb/GnbMobileSideBar.tsx
  src/shared/ui/gnb/GnbProductSearchInput.tsx
  src/shared/ui/gnb/GnbSearchButton.tsx
  src/shared/ui/gnb/index.ts
  src/shared/ui/product-card/ProductCardItem.tsx
  src/shared/ui/product-card/ProductCardList.tsx
  src/widgets/product/product-home/components/category-menu/CategoryItems.tsx
  src/widgets/product/product-home/components/category-menu/CategoryMenu.tsx
  src/widgets/product/product-home/components/category-menu/SideMenu.stories.ts
  src/widgets/product/product-home/components/category-menu/index.ts
  src/widgets/product/product-home/components/index.ts
  src/widgets/product/product-home/components/product-hot/ProductHot.tsx
  src/widgets/product/product-home/components/product-rating/ProductRating.tsx
  src/widgets/product/product-home/components/ranking/Ranking.tsx
  src/widgets/product/product-home/components/side-menu/MenuTaps.tsx
  src/widgets/product/product-home/components/side-menu/SideMenu.tsx
  src/widgets/product/product-home/components/side-menu/SideMenuMobile.tsx
  src/widgets/product/product-home/components/side-menu/index.ts
Labels: ♻️ Refactor

#130 ♻️ Refactor: 프로덕트 쿼리 키 설정
  src/shared/hooks/mutate/index.ts
  src/shared/hooks/mutate/product-detail.mutate.ts
  src/shared/hooks/mutate/product.mutate.ts
  src/shared/hooks/mutate/review.mutate.ts
  src/shared/hooks/query-keys/index.ts
  src/shared/hooks/query-keys/product.key.ts
  src/shared/hooks/query/index.ts
  src/shared/hooks/query/product-detail.query.ts
  src/shared/hooks/query/product.query.ts
  src/shared/hooks/query/review.query.ts
  src/shared/types/product/product-review.type.ts
  src/shared/ui/category-chip/CategoryChip.type.ts
  src/shared/ui/gnb/GnbProductSearchInput.tsx
  src/widgets/compare/hooks/useProductAutocomplete.ts
  src/widgets/product/product-detail/components/product-info/product-contents/LikeButton.tsx
  src/widgets/product/product-detail/components/review/contents/ReviewContents.tsx
  src/widgets/product/product-detail/components/review/contents/delete-button/ReviewDeleteButton.tsx
  src/widgets/product/product-home/components/product-rating/ProductRating.tsx
Labels: ♻️ Refactor

#132 ♻️ Refactor: user 쿼리 키 정리
  src/shared/api/user.api.ts
  src/shared/hooks/mutate/follow.mutate.ts
  src/shared/hooks/mutate/user.mutate.ts
  src/shared/hooks/query-keys/index.ts
  src/shared/hooks/query-keys/user.key.ts
  src/shared/hooks/query/user.query.ts
  src/shared/types/user/user.type.ts
  src/widgets/profile/components/activity-log-section/ActivityLogSection.tsx
  src/widgets/profile/components/product-card-section/products/CreatedProducts.tsx
  src/widgets/profile/components/product-card-section/products/FavoriteProducts.tsx
  src/widgets/profile/components/product-card-section/products/ProductsList.tsx
  src/widgets/profile/components/product-card-section/products/ReviewedProducts.tsx
  src/widgets/profile/components/product-card-section/section/ProductCardSection.tsx
  src/widgets/profile/components/profile-card/card-contents/FolloweesButton.tsx
  src/widgets/profile/components/profile-card/card-contents/FollowerButton.tsx
  src/widgets/profile/components/profile-card/card-contents/ProfileStats.tsx
  src/widgets/profile/components/profile-follow-modal/followees-list/FolloweesList.tsx
  src/widgets/profile/components/profile-follow-modal/follower-list/FollowerList.tsx
  src/widgets/profile/components/profile-follow-modal/modal/ProfileFolloweesModal.tsx
  src/widgets/profile/components/profile-follow-modal/modal/ProfileFollowerModal.tsx
Labels: ♻️ Refactor

#133 ♻️ refactor: categoryMenu 분리, 메인페이지 ui 수정, 로그인에 따른 menu 분기처리
  pages/404.tsx
  pages/_app.tsx
  pages/index.tsx
  pages/product/[id]/index.tsx
  src/pages/product/Product.tsx
  src/shared/hooks/useToggle.ts
  src/shared/ui/gnb/Gnb.tsx
  src/shared/ui/gnb/GnbMenu.tsx
  src/shared/ui/gnb/GnbMobileSideBar.tsx
  src/shared/ui/product-card/ProductCardItem.tsx
  src/widgets/product/product-home/components/category-menu/CategoryMenu.tsx
  src/widgets/product/product-home/components/ranking/Ranking.tsx
Labels: ✨ Feature

#135 ♻️/🐛 Refactor/Fix: profile페이지 공통컴포넌트 product-card 사용 및 404이미지 에러 수정
  pages/404.tsx
  src/shared/hooks/useWindowResize.ts
  src/shared/types/user/user.type.ts
  src/shared/ui/product-card/ProductCardItem.tsx
  src/shared/ui/product-card/ProductCardList.tsx
  src/widgets/profile/MockCardItem.tsx
  src/widgets/profile/components/product-card-section/index.ts
  src/widgets/profile/components/product-card-section/products/CreatedProducts.tsx
  src/widgets/profile/components/product-card-section/products/FavoriteProducts.tsx
  src/widgets/profile/components/product-card-section/products/ProductsList.tsx
  src/widgets/profile/components/product-card-section/products/ReviewedProducts.tsx
  src/widgets/profile/components/product-card-section/section/ProductCardSection.tsx
  src/widgets/profile/components/product-card-section/wrapper/ProductWrapper.tsx
Labels: 🐛 Bug, ♻️ Refactor

#136 🐛 Fix: 상품 상세 페이지 오류 수정
  pages/api/google/signUp.ts
  pages/product/[id]/index.tsx
  pages/profile/[id]/index.tsx
  src/pages/product/detail/ProductDetail.tsx
  src/shared/hooks/useWindowResize.ts
  src/shared/ui/gnb/GnbMenu.tsx
  src/shared/utils/token.utils.ts
  src/widgets/auth/hooks/useSignIn.ts
  src/widgets/compare/hooks/useProductAutocomplete.ts
  src/widgets/product/product-detail/components/product-info/info/ProductInfo.tsx
  src/widgets/product/product-detail/components/product-info/product-contents/ProductContents.tsx
  src/widgets/profile/components/product-card-section/section/ProductCardSection.tsx
Labels: 🐛 Bug

#138 ✨ Feat: 카테고리 페이지 추가
  pages/category/[id]/index.tsx
  pages/product/category/[id]/index.tsx
  src/pages/index.ts
  src/pages/product/category/ProductCategoryPage.tsx
  src/shared/ui/category-chip/CategoryChip.type.ts
  src/shared/ui/product-card/ProductCardList.tsx
  src/widgets/product/product-home/components/category-menu/CategoryItems.tsx
  src/widgets/product/product-home/components/category-menu/CategoryMenu.tsx
  src/widgets/product/product-home/components/index.ts
  src/widgets/product/product-home/components/product-empty/ProductEmpty.tsx
Labels: ✨ Feature, 💄 UI

#140 ✨/🐛 Feat/Fix: image-fallback hook 제작 및 이미지 컴포넌트 에러 해결
  pages/404.tsx
  public/images/default-product.svg
  src/shared/hooks/useImageFallback.ts
  src/shared/icons/index.ts
  src/shared/ui/gnb/Gnb.tsx
  src/shared/ui/product-card/ProductCardItem.tsx
  src/shared/ui/profile-image/ProfileImage.tsx
  src/widgets/product/product-detail/components/product-info/product-image/ProductImage.tsx
  src/widgets/product/product-detail/components/review/contents/review-images/ReviewImages.tsx
  src/widgets/product/product-detail/components/review/list/ReviewEmptyList.tsx
  src/widgets/product/product-detail/components/review/profile/ReviewProfile.tsx
  src/widgets/product/product-home/layout/ProductCardSection.tsx
  src/widgets/profile/components/product-card-section/products/EmptyProduct.tsx
Labels: ✨ Feature, 🐛 Bug

#142 ✨ Feat: follow list skeleton 및 프로필 편집 모달 default 값 적용
  pages/profile/my/index.tsx
  src/widgets/profile/components/profile-edit-modal/form/ProfileEditForm.tsx
  src/widgets/profile/components/profile-edit-modal/form/defaultValues.ts
  src/widgets/profile/components/profile-edit-modal/image-upload/ProfileImageUpload.tsx
  src/widgets/profile/components/profile-follow-modal/index.ts
  src/widgets/profile/components/profile-follow-modal/modal/ProfileFolloweesModal.tsx
  src/widgets/profile/components/profile-follow-modal/modal/ProfileFollowerModal.tsx
  src/widgets/profile/components/profile-follow-modal/skeleton/FollowListSkeleton.tsx
Labels: ✨ Feature

#141 ✨ Feat: 헤더 인증에 따른 메뉴 보여주기
  pages/product/[id]/index.tsx
  pages/product/category/[id]/index.tsx
  pages/profile/[id]/index.tsx
  pages/profile/my/index.tsx
Labels: ✨ Feature

#145 ✨ Feat: 페이지 SEO 처리하기
  package.json
  pages/404.tsx
  pages/_app.tsx
  pages/_document.tsx
  pages/index.tsx
  pages/product/[id]/index.tsx
  pages/product/category/[id]/index.tsx
  pages/profile/[id]/index.tsx
  public/images/favicon.ico
  public/images/seo-image.jpg
  src/pages/product/category/ProductCategoryPage.tsx
  src/widgets/product/product-home/components/index.ts
  src/widgets/profile/components/profile-card/card-contents/ProfileHeader.tsx
  yarn.lock
Labels: ✨ Feature

#147 🐛 Fix: social에서 로컬 스토리지 접근 안되는 버그
  pages/api/google/signIn.ts
  pages/api/google/signUp.ts
  pages/api/kakao/signIn.tsx
  pages/api/kakao/signup.tsx
  src/shared/utils/toast-check-auth.utils.ts
  src/shared/utils/token.utils.ts
Labels: 🐛 Bug

#148 ✨ [#144] Feat: SEO 누락된 페이지 추가
  pages/auth/oauth-sign-up/google.tsx
  pages/auth/oauth-sign-up/kakao.tsx
  pages/auth/sign-in/index.tsx
  pages/auth/sign-up/index.tsx
  src/pages/auth/sign-up/SignUpPage.tsx
Labels: ✨ Feature

#149 💄 UI : ProductCard 스켈레톤 작업
  src/pages/product/Product.tsx
  src/pages/product/category/ProductCategoryPage.tsx
  src/shared/hooks/query/product.query.ts
  src/shared/ui/product-card/ProductCardItem.tsx
  src/shared/ui/product-card/ProductCardSkeleton.tsx
  src/widgets/compare/hooks/useProductAutocomplete.ts
  src/widgets/product/product-home/components/product-empty/ProductEmpty.tsx
  src/widgets/product/product-home/components/product-searched/index.tsx
  src/widgets/profile/components/product-card-section/wrapper/ProductWrapper.tsx
Labels: 💄 UI

#154 ✨ Feat: 스토리북 버튼 수정
  .storybook/main.ts
  .storybook/preview.ts
  src/app/styles/globals.css
  src/app/styles/stories.css
  src/shared/ui/button/Button.mdx
  src/shared/ui/button/Button.stories.tsx
  src/widgets/product/product-detail/storybook/ProductInfo.stories.tsx
  src/widgets/product/product-detail/storybook/Review.stories.tsx
  src/widgets/product/product-detail/storybook/Statistics.stories.tsx
Labels: 📝 Documentation

#158 ✨ Feat: 카테고리 칩 스토리북 추가
  src/shared/ui/category-chip/Category.mdx
  src/shared/ui/category-chip/CategoryChip.stories.tsx
  src/shared/ui/category-chip/CategoryChip.tsx
Labels: ✨ Feature, 📝 Documentation

#166 🐛 Fix: 일정 스크롤시 모달이 fixed 안되어 있는 UI 버그
  src/pages/profile/Profile.tsx
  src/shared/hooks/useLogout.ts
  src/shared/store/index.ts
  src/shared/store/userStore.ts
  src/shared/ui/form-field/FormField.stories.tsx
  src/shared/ui/input/image-input/ImageInput.stories.tsx
  src/shared/ui/input/text-box-input/TextBoxInput.tsx
  src/shared/ui/input/text-box-input/TextBoxInput.type.ts
  src/shared/ui/input/text-field-input/TextFieldInput.stories.tsx
  src/shared/ui/input/textarea-input/TextareaInput.stories.tsx
  src/shared/ui/modal/Modal.tsx
  src/shared/ui/product-card/ProductCardItem.tsx
  src/shared/utils/toast-check-auth.utils.ts
  src/shared/utils/token.utils.ts
  src/widgets/auth/hooks/useSignIn.ts
  src/widgets/auth/hooks/useSignUp.ts
Labels: 🐛 Bug

#162 ✨ Feat: 카테고리 드롭다운 스토리북
  src/shared/ui/button/Button.mdx
  src/widgets/product/common/category-dropdown/CategoryDropdown.mdx
  src/widgets/product/common/category-dropdown/CategoryDropdown.stories.tsx
Labels: ✨ Feature, 📝 Documentation

#169 💄 storybook : ranking, productCard mdx 작성
  .storybook/main.ts
  .storybook/preview-body.html
  .storybook/preview.tsx
  package.json
  public/mockServiceWorker.js
  src/app/styles/stories.css
  src/shared/hooks/useImageFallback.ts
  src/shared/types/product/product.type.ts
  src/shared/ui/product-card/ProductCardItem.mdx
  src/shared/ui/product-card/ProductCardItem.stories.tsx
  src/shared/ui/product-card/ProductCardItem.tsx
  src/shared/ui/product-card/ProductCardSkeleton.stories.tsx
  src/shared/ui/profile-image/ProfileImage.tsx
  src/widgets/product/product-home/components/product-hot/ProductListExample.stories.tsx
  src/widgets/product/product-home/components/ranking/Ranking.mdx
  src/widgets/product/product-home/components/ranking/Ranking.stories.tsx
  src/widgets/product/product-home/components/ranking/Ranking.tsx
  src/widgets/product/product-home/components/ranking/RankingItem.stories.tsx
  src/widgets/product/product-home/components/ranking/RankingItem.tsx
  src/widgets/product/product-home/storybook/ProductModal.stories.tsx
  tsconfig.json
  yarn.lock
Labels: 📝 Documentation, 💄 UI

#174 ♻️ Refactor: 상품 추가 모달 리팩토링, 스토리북 post 시 실제 입력 데이터 기반으로 적용
  .storybook/preview.tsx
  src/pages/product/Product.tsx
  src/pages/product/category/ProductCategoryPage.tsx
  src/widgets/product/common/category-dropdown/CategoryDropdown.stories.tsx
  src/widgets/product/product-detail/components/product-info/product-image/ProductImage.tsx
  src/widgets/product/product-detail/components/review-modal/modal/ReviewCreateModal.stories.tsx
  src/widgets/product/product-home/components/index.ts
  src/widgets/product/product-home/components/product-add-modal/index.ts
  src/widgets/product/product-home/components/product-add-modal/modal/ProductAddModal.stories.tsx
  src/widgets/product/product-home/components/product-create-button/ProductCreateButton.tsx
  src/widgets/product/product-home/components/product-create-modal/form/ProductCreateForm.tsx
  src/widgets/product/product-home/components/product-create-modal/form/defaultValues.ts
  src/widgets/product/product-home/components/product-create-modal/index.ts
  src/widgets/product/product-home/components/product-create-modal/modal/ProductCreateModal.stories.tsx
  src/widgets/product/product-home/components/product-create-modal/modal/ProductCreateModal.tsx
  src/widgets/product/product-home/components/product-empty/ProductEmpty.tsx
Labels: ✨ Feature

#179 ♻️ Refactor: 스토리북 구조 리팩토링
  src/widgets/product/common/category-dropdown/CategoryDropdown.stories.tsx
  src/widgets/product/common/sort-dropdown/SortDropdown.stories.tsx
Labels: ♻️ Refactor

#181 ✨ Feat: 모달 스토리북 추가
  src/shared/ui/modal/Modal.mdx
  src/shared/ui/modal/Modal.stories.tsx
  src/widgets/product/product-home/components/product-create-modal/modal/ProductCreateModal.stories.tsx
Labels: ✨ Feature, 📝 Documentation

#183 ✨ Feat: MSW Handler 관리하는 mock 폴더 추가
  src/shared/mocks/index.ts
  src/shared/mocks/product/index.tsx
  src/shared/mocks/review/index.ts
  src/shared/mocks/upload/index.tsx
  src/widgets/product/product-detail/components/product-update-modal/modal/ProductUpdateModal.stories.tsx
  src/widgets/product/product-detail/components/review-modal/modal/ReviewCreateModal.stories.tsx
  src/widgets/product/product-detail/components/review-modal/modal/ReviewUpdateModal.stories.tsx
  src/widgets/product/product-home/components/product-create-modal/modal/ProductCreateModal.stories.tsx
  tsconfig.json
Labels: ✨ Feature

#185 💄Design: 스크롤바 커스텀으로 변경 또는 스크롤바 ui 없애기
  src/shared/ui/dropdown/Dropdown.tsx
  src/shared/ui/input/textarea-input/TextareaInput.tsx
  src/widgets/product/product-detail/components/review-modal/form/ReviewCreateForm.tsx
  src/widgets/product/product-detail/components/review-modal/form/ReviewUpdateForm.tsx
  src/widgets/product/product-home/components/ranking/Ranking.tsx
Labels: 💄 UI

#187 💄 Design: 프로필 Sticky 적용
  middleware.ts
  src/widgets/profile/components/profile-card/card/MyProfileCard.tsx
  src/widgets/profile/components/profile-card/card/UserProfileCard.tsx
Labels: ✨ Feature

#189 ✨ Feat: 리뷰 스토리북
  .storybook/preview.tsx
  src/shared/mocks/review/index.ts
  src/widgets/product/product-detail/components/review/Review.stories.tsx
  src/widgets/product/product-detail/components/review/contents/ReviewContents.tsx
Labels: ✨ Feature

#193 🐛 Fix: 프로필 페이지 관련 에러 해결
  pages/profile/[id]/index.tsx
  src/pages/profile/Profile.tsx
  src/shared/hooks/index.ts
  src/shared/hooks/useClientSide.ts
  src/shared/ui/autocomplete-field/AutocompleteField.type.ts
  src/shared/ui/category-chip/CategoryChip.constants.ts
  src/shared/ui/category-chip/CategoryChip.tsx
  src/shared/ui/product-card/ProductCardItem.tsx
  src/widgets/profile/components/activity-log-section/LogList.tsx
  src/widgets/profile/components/activity-log-section/LogListItem.tsx
  src/widgets/profile/components/profile-card/card/MyProfileCard.tsx
  src/widgets/profile/components/profile-card/card/UserProfileCard.tsx
  src/widgets/profile/components/profile-follow-modal/follow/Follow.tsx
Labels: 🐛 Bug

#197 🐛 Fix: 타입 에러 해결
  src/shared/types/user/user.type.ts
  src/widgets/profile/components/profile-follow-modal/followees-list/FolloweesList.tsx
  src/widgets/profile/components/profile-follow-modal/follower-list/FollowerList.tsx
Labels: 🐛 Bug

#200 🐛 [#199] Fix: 파비콘 안나오는 문제 해결
  pages/_document.tsx
Labels: 🐛 Bug

#202 🐛 Fix: Pretendard Subset으로 변경
  pages/_document.tsx
  pages/index.tsx
  public/assets/fonts/Pretendard-Bold.subset.woff2
  public/assets/fonts/Pretendard-Medium.subset.woff2
  public/assets/fonts/Pretendard-Regular.subset.woff2
  public/assets/fonts/Pretendard-SemiBold.subset.woff2
  src/app/styles/fonts.css
  src/app/styles/globals.css
Labels: 🐛 Bug

#205 ♻️ refactor : compare 페이지 로직 수정 및 ui변경
  pages/product/[id]/compare/index.tsx
  src/app/styles/globals.css
  src/pages/compare/index.tsx
  src/pages/product/Product.tsx
  src/shared/hooks/query/product.query.ts
  src/shared/ui/gnb/GnbHamburgerButton.tsx
  src/shared/ui/gnb/GnbSearchButton.tsx
  src/widgets/compare/components/CompareInput.tsx
  src/widgets/product/product-detail/components/product-info/product-contents/ProductContents.tsx
  src/widgets/product/product-home/components/category-menu/CategoryMenu.tsx
  src/widgets/product/product-home/components/product-hot/ProductHot.tsx
  src/widgets/product/product-home/components/product-rating/ProductRating.tsx
  src/widgets/product/product-home/components/ranking/Ranking.tsx
  src/widgets/product/product-home/components/ranking/RankingItem.tsx
Labels: ♻️ Refactor

#217 bug수정
  pages/product/category/[id]/index.tsx
  src/pages/compare/index.tsx
  src/shared/hooks/query/ranking.query.ts
  src/shared/ui/gnb/GnbMobileSideBar.tsx
  src/shared/ui/gnb/GnbProductSearchInput.tsx
  src/shared/ui/gnb/utils/handleListByKeyboard.ts
  src/shared/ui/product-card/ProductCardItem.tsx
  src/shared/utils/kIndexet.ts
  src/widgets/compare/hooks/useProductAutocomplete.ts
  src/widgets/product/product-detail/components/review/contents/thumbs-button/ThumbsButton.tsx
  src/widgets/product/product-detail/components/statistics/calculate/helper/StarRatingMessage.tsx
  src/widgets/product/product-home/components/category-menu/CategoryDropDown.tsx
  src/widgets/product/product-home/components/product-rating/ProductRating.tsx
  src/widgets/product/product-home/components/product-searched/index.tsx
  src/widgets/product/product-home/components/ranking/Ranking.tsx
  src/widgets/product/product-home/components/ranking/RankingItem.tsx
  src/widgets/product/product-home/layout/ProductCardSection.tsx
  src/widgets/profile/components/profile-card/card-contents/FolloweesButton.tsx
  src/widgets/profile/components/profile-card/card-contents/FollowerButton.tsx
Labels: 🐛 Bug

#219 🐛 Fix: Review 수정 시 날짜 바뀌는 문제.
  src/widgets/product/product-detail/components/review/contents/ReviewContents.tsx
Labels: 🐛 Bug

#225 🐛 Fix: 프로필 수정 사항 및 기타 에러 해결
  pages/_app.tsx
  pages/api/kakao/signUp.tsx
  src/pages/auth/sign-in/SignInPage.tsx
  src/pages/auth/sign-up/SignUpPage.tsx
  src/shared/constants/social.constants.ts
  src/shared/ui/input/image-input/ImageInput.tsx
  src/widgets/auth/components/sign-in-field/SignInField.tsx
  src/widgets/auth/components/sign-up-field/SignUpField.tsx
  src/widgets/profile/components/profile-edit-modal/form/ProfileEditForm.tsx
  src/widgets/profile/components/profile-edit-modal/image-upload/ProfileImageUpload.tsx
  src/widgets/profile/components/profile-follow-modal/followees-list/FolloweesList.tsx
  src/widgets/profile/components/profile-follow-modal/follower-list/FollowerList.tsx
Labels: 🐛 Bug

#223 ✨ feat : product url검색기능 추가
  pages/_app.tsx
  src/pages/compare/index.tsx
  src/pages/product/Product.tsx
  src/pages/product/category/ProductCategoryPage.tsx
  src/shared/hooks/query/product.query.ts
  src/shared/store/productStore.ts
  src/shared/ui/gnb/Gnb.tsx
  src/shared/ui/gnb/GnbMenu.tsx
  src/shared/ui/gnb/GnbProductSearchInput.tsx
  src/shared/ui/gnb/utils/handleListByKeyboard.ts
  src/widgets/compare/components/CompareInput.tsx
  src/widgets/compare/components/CompareSheet.tsx
  src/widgets/compare/hooks/useProductAutocomplete.ts
  src/widgets/product/product-home/components/category-menu/CategoryDropDown.tsx
  src/widgets/product/product-home/components/category-menu/CategoryMenu.tsx
  src/widgets/product/product-home/components/ranking/Ranking.tsx
Labels: ✨ Feature

#231 🐛 Fix: 상품 추가 모달 로딩 처리
  src/widgets/product/product-home/hooks/useProductAddForm.ts
Labels: 🐛 Bug
